# Generated by Django 4.0.6 on 2023-04-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
