# Generated by Django 4.2.1 on 2023-05-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_product_preview_product_views_count_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='archived',
        ),
    ]
