# Generated by Django 4.1.4 on 2023-05-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_remove_cart_total_price_alter_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
