# Generated by Django 4.1.4 on 2023-05-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
