# Generated by Django 4.1.4 on 2023-05-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
