# Generated by Django 4.1.4 on 2023-05-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0018_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
